redis:
  image: redis
   
  expose:
    - 6379
  ports:
    - "6379:6379"
app:
  build: ./
  volumes:
    - ./:/var/www/app
  links:
    - redis
  ports:
    - 8801:8801
  environment:
    - REDIS_URL=redis://cache
    - NODE_ENV=development
    - PORT=8801
  command:
    sh -c 'npm i && node server.js'

